# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: mysql2
  encoding: utf8
  database: rollreport_development
  pool: 5
  username: root
  password: password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: rollreport_test
  pool: 5
  username: root
  password: password
  host: localhost

